export const PENDING_CALL = 'PENDING_CALL';
export const FAILED_CALL = 'FAILED_CALL';
export const RECEIVE_INITIAL_EVENTS = 'RECEIVE_INITIAL_EVENTS';
export const SHOW_EVENT_MODAL = 'SHOW_EVENT_MODAL';
